### ISSUE TITLE
verifying signature without setting data, extracting data after verification

### ISSUE THREAD

**Issue by aoberoi** [deceze/Kunststube-CSRFP#4]
Thanks for this library, it is great!

I have a use case where I'd like to verify a token signature on an incoming request, and then extract the data stored in the token (since I've already proven its authenticity). As of now, I'd have to set the data on the instance of `SignatureGenerator` before verifying the signature. If I know exactly which data is set, then this is possible, but for arbitrary data, I'm stuck.

It seems reasonable to expect the `SignatureGenerator::validateSignature()` method to do this work for me since it already encapsulates the serialization and signing logic. Are there any technical or security reasons why I must set the data before invoking this method?

**Comment by deceze** [comment]
I'm not entirely sure I understand your issue. "Arbitrary data" means your form contains fields you don't know in advance? Then those fields simply cannot be validated using this library. A CSRFP token can only prove certain things, specifically that whoever generated the token was in possession of certain information. Most notably the generator must have been in possession of the `$secret`, which (should) prove that it was you who generated the token.

You can add additional data to also prove that whoever generated the token expected exactly that data to be present at the time of validation. You can use that however you want. What you cannot do is reverse that information; i.e. you cannot get that data back from the token. You must feed the same data back into the token generator, you cannot "extract" it back from the generator.

Having said this, can you clarify what work you'd like `SignatureGenerator::validateSignature()` to do exactly?

**Comment by aoberoi** [comment]
Thanks for responding. I think i misunderstood the use cases for this library. It turns out that I'm no longer working on the project where I was using this library, so feel free to dismiss this issue.
