### ISSUE TITLE
Token on Ajax Request

### ISSUE THREAD

**Issue by AkinOlawale** [deceze/Kunststube-CSRFP#6]
Hi. Can this class be used for ajax requests?

**Comment by deceze** [comment]
Sure, fundamentally yes. The tricky part is to return a fresh token from the server for each request. E.g., if your tokens expire within an hour, and you only send a token from the server to the browser on page load, and that page sits there for an hour after which you make a request, your token will be expired. You'll need to be very careful with CORS when you request a new token from your server, so as not to subvert the entire mechanism by allowing anyone to fetch a token at any time from anywhere.

Also note that this library hasn't been touched in forever. It still works AFAIK, but it's unmaintained.
